### ISSUE TITLE
Double SIM

### ISSUE THREAD

**Issue by hectorgarm** [vegetalte-dev/android_device_bq_vegetalte#1]
I can't find the option to enable/disable one of the SIM cards manually. Since I upgrade to CM13 both SIMs are always enabled.

**Comment by Kra1o5** [comment]
Hi @hectorgarm ,

Is upstream problem.

Probably CM implement it soon.

Greetings

**Comment by Kra1o5** [comment]
Please, see this: https://github.com/vegetalte-dev/android_device_bq_vegetalte/issues/10

Greetings
