### ISSUE TITLE
Radio FM

### ISSUE THREAD

**Issue by hectorgarm** [vegetalte-dev/android_device_bq_vegetalte#2]
When listening to the radio with headset and I disconect the headset the radio turns off (as is supposed to do), but about 2 seconds after that, the phone speaker starts to make a sound as if the radio is on but no signal received (you know that sound when you turn on a radio in no channel). This goes on just for half a second or so.

**Comment by Kra1o5** [comment]
Hi @hectorgarm ,

I will check it.

**Comment by Kra1o5** [comment]
Please, see this: https://github.com/vegetalte-dev/android_device_bq_vegetalte/issues/10

Greetings
