### ISSUE TITLE
Wifi consumption 

### ISSUE THREAD

**Issue by hectorgarm** [vegetalte-dev/android_device_bq_vegetalte#3]
![screenshot_20160312-110736](https://cloud.githubusercontent.com/assets/17690386/13722366/2f8053e4-e843-11e5-9224-57cf87ebbcd8.png)
As you can see in the screenshot,  when my phone is off, wifi is activated and consuming battery

**Comment by Kra1o5** [comment]
Hi @hectorgarm ,

Is android bug not device or cm specific.

But dont worry is a UI error.

**Comment by Kra1o5** [comment]
Please, see this: https://github.com/vegetalte-dev/android_device_bq_vegetalte/issues/10

Greetings
