### ISSUE TITLE
Sensitive notifications still show on lockscreen

### ISSUE THREAD

**Issue by JoaoRabit** [vegetalte-dev/android_device_bq_vegetalte#4]
I have Facebook Messenger's notifications set as sensitive but it still shows the messages content on the lock screen.

**Comment by Kra1o5** [comment]
Hi @JoaoRabit ,

Sorry I dont use this app, @eloimuns can you check it please?

**Comment by JoaoRabit** [comment]
This isn't a bug specific to Facebook's Messenger because I also have the Google's Messaging app set as sensitive and both still show the content on the lockscreen as you can see from the screenshot below.
![screenshot_20160313-191200](https://cloud.githubusercontent.com/assets/16391205/13730750/153180ae-e950-11e5-969b-95ad95b08d8b.png)

**Comment by JoaoRabit** [comment]
With the latest update (13-03-2016) the issue seems to be fixed.
