### ISSUE TITLE
Priority notifications don't work

### ISSUE THREAD

**Issue by JoaoRabit** [vegetalte-dev/android_device_bq_vegetalte#5]
I have the messaging app set as priority notification but when I set Do Not Disturb to priority notifications only it doesn't notify me as if it wasn't set as priority.

**Comment by Kra1o5** [comment]
Hi @JoaoRabit ,

I cant reproduce it, 

What apps you use?

Greetings

**Comment by JoaoRabit** [comment]
Hi
Stange... now it's working.
Well i suppose it wasn't really a issue. My bad.
