### ISSUE TITLE
Alarm clock

### ISSUE THREAD

**Issue by hectorgarm** [vegetalte-dev/android_device_bq_vegetalte#6]
Since the last update dated 13/03/2016 the alarm clock aplication fails when trying to switch an alarm off.

It gives an error and stop working.

**Comment by Kra1o5** [comment]
Hi @hectorgarm ,

Yes is upstream issue.

As a workaround you can use Google Clock app from Play Store.

We will release new build asap bug get fixed.

Greetings

**Comment by Kra1o5** [comment]
Seems to be fixed upstream: https://github.com/CyanogenMod/android_frameworks_support/commit/9ac291bad6edb745d68aab9baf0465c3323d8e4e & will be fixed in todays build.
