### ISSUE TITLE
Whatsupp voice messages not reproduced (aac format)

### ISSUE THREAD

**Issue by raulillo82** [vegetalte-dev/android_device_bq_vegetalte#8]
Hi,

whatsapp voice messages cannot be reproduced from inside the app. I've noticed they're stored in aac format, which I cannot open with any "standard" app. They can be opened with vlc though, for instance.
Some people have reported that short voice messages (< 10s) work though, although I don't have any to confirm. Might those be stored in another format?

**Comment by Kra1o5** [comment]
Hi @raulillo82 ,

Its in CM13.0?

Greetings

**Comment by raulillo82** [comment]
Looks like I cannot reproduce it any more, so this can be canceled.

**Comment by Kra1o5** [comment]
Please, see this: https://github.com/vegetalte-dev/android_device_bq_vegetalte/issues/10

Greetings
