### ISSUE TITLE
Handsfree dualSIM

### ISSUE THREAD

**Issue by nunocspinto** [vegetalte-dev/android_device_bq_vegetalte#9]
I use my smartphone as handsfree in my car (2015 Hyundai i10, if it matters) and with 5.1 official, I had an option in Settings to associate a SIM to Handsfree mode, so when I make a call using the car voice regognition system or the contact list, it uses only one SIM card.
In this version, when I make a call with one of the systems:
1 - the phone doesn't wake up automatically;
2 - when the phone is awake, doesn't prompt the SIM card choice menu,
making the use of handsfree useless, because I always need to touch the phone to make a call on the go.
What can you do to this?

**Comment by Kra1o5** [comment]
Hi you refer to CM13.0?

Greetings

**Comment by nunocspinto** [comment]
Yes I do

Nuno Campos

Enviado do Outlook Mobile

On Sun, Apr 17, 2016 at 1:49 AM -0700, "Alejandro Lopez" notifications@github.com wrote:

Hi you refer to CM13.0?

Greetings

---

**Comment by Kra1o5** [comment]
Please, see this: https://github.com/vegetalte-dev/android_device_bq_vegetalte/issues/10

Greetings
